language: haskell
notifications:
  email: false
before_install:
- sudo apt-get update
- sudo apt-get install gnupg
script:
- cabal configure --enable-tests && cabal build && cabal test hlint
- bash tests/deploy-haddock.sh
env:
  global:
    secure: iMV7EbAdq5e6vahE9ztVAFuk5keeRr4HwJ4NJmLfTdzgO1ixg3V0pfYbfDx3xW5/qSdTTH7TTRX9kOuO8yuJz8HJGIvCkyDAearKSRzOCqpsdqORFI/XltcGogjm/xZWubFZEikL6D+iHe3i9KLL2rbzwI3czwWpCMplkqyVPEU=
